export const PERMISSION = {
  POST_VIEW: 'POST_VIEW',
  POST_CREATE: 'POST_CREATE',
  POST_EDIT: 'POST_EDIT',
  POST_DELETE: 'POST_DELETE',
  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_EDIT: 'PERMISSION_EDIT',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  USER_MANAGER_VIEW: 'USER_MANAGER_VIEW',
  USER_MANAGER_CREATE: 'USER_MANAGER_CREATE',
  USER_MANAGER_EDIT: 'USER_MANAGER_EDIT',
  USER_MANAGER_DELETE: 'USER_MANAGER_DELETE',
};

export default {};